#!/usr/bin/env bash
# authority.sh — run the grant authority locally, on :8799 as before.
#
# It now runs the DEPLOYED codebase (apps/grant-authority, `wrangler dev`)
# rather than the old scripts/grant-authority.mjs node service. One
# implementation, exercised locally every day and deployed unchanged — the
# alternative is two grant faucets that drift, and the one that drifts is the
# one holding K(L) of both authority logs.
#
# The deployed Worker takes its wiring from secrets and vars. Locally that has
# to come from somewhere, so this script GENERATES apps/grant-authority/.dev.vars
# from the two sources that already hold it:
#
#   .provision/   ids.env, authority.es256.pem, {agent,user}-auth-grant.b64
#   doppler       COORDINATOR_APP_TOKEN (canopy/dev)
#
# The generated file is gitignored and rewritten on every run, so re-provisioning
# is picked up without a manual edit. Override any value by exporting it first.
set -euo pipefail
cd "$(dirname "$0")/.."

PROVISION=.provision
APP=apps/grant-authority
PORT="${PORT:-8799}"

[ -f "$PROVISION/ids.env" ] || {
	echo "authority.sh: no $PROVISION/ids.env — run provision.sh up first" >&2
	exit 1
}

# shellcheck disable=SC1090,SC1091  # generated by provision.sh, not in the repo
. "$PROVISION/ids.env"

: "${ROOT_LOG_ID:?ids.env has no ROOT_LOG_ID}"
: "${AGENT_AUTH_LOG_ID:?ids.env has no AGENT_AUTH_LOG_ID — re-provision for the W4b.1 two-log shape}"
: "${USER_AUTH_LOG_ID:?ids.env has no USER_AUTH_LOG_ID — re-provision for the W4b.1 two-log shape}"

if [ -z "${COORDINATOR_APP_TOKEN:-}" ]; then
	COORDINATOR_APP_TOKEN=$(doppler secrets get COORDINATOR_APP_TOKEN \
		--project canopy --config dev --plain 2>/dev/null || true)
	[ -n "$COORDINATOR_APP_TOKEN" ] ||
		echo "authority.sh: no COORDINATOR_APP_TOKEN (doppler fetch failed) — user grants will fail" >&2
fi

# The Worker holds the authority key as a JWK, not a PEM: JWK carries BOTH key
# halves in one string, and delegation-cose needs an extractable public half that
# a PKCS#8 private key cannot give back. Converted here so .provision keeps its
# PEM and nothing new has to be provisioned.
AUTHORITY_ES256_JWK=$(node -e '
	const { createPrivateKey } = require("node:crypto");
	const pem = require("node:fs").readFileSync(process.argv[1], "utf8");
	process.stdout.write(JSON.stringify(createPrivateKey(pem).export({ format: "jwk" })));
' "$PROVISION/authority.es256.pem")

# A local bearer is generated per run rather than left unset: the Worker refuses
# to serve anything but /healthz without one (deployed it is an open grant
# faucet), so an unset token would make local dev diverge from deployed exactly
# where it matters. Export GRANT_AUTHORITY_TOKEN to pin it across restarts —
# scribe-worker's .dev.vars must carry the same value.
GRANT_AUTHORITY_TOKEN="${GRANT_AUTHORITY_TOKEN:-$(openssl rand -hex 16)}"

umask 077
cat >"$APP/.dev.vars" <<EOF
# GENERATED by scripts/authority.sh — do not edit, do not commit.
AUTHORITY_ES256_JWK='$AUTHORITY_ES256_JWK'
GRANT_AUTHORITY_TOKEN='$GRANT_AUTHORITY_TOKEN'
COORDINATOR_APP_TOKEN='${COORDINATOR_APP_TOKEN:-}'
FORESTRIE_BASE_URL='${FORESTRIE_BASE_URL:-https://api-a.forest-2.forestrie.dev}'
DELEGATION_COORDINATOR_URL='${DELEGATION_COORDINATOR_URL:-https://coordinator-a.forest-2.forestrie.dev}'
KNOWN_SEALER_KEY='${KNOWN_SEALER_KEY:-z1YarLKXrsRe5egrwrFfbeYadd9lOqplKxbRuMGymHUOSY7YAfdOhhPWb3H72TrPMiMLw0CBMpDPXUGMEvbkOQ==}'
ROOT_LOG_ID='$ROOT_LOG_ID'
AGENT_AUTH_LOG_ID='$AGENT_AUTH_LOG_ID'
USER_AUTH_LOG_ID='$USER_AUTH_LOG_ID'
AGENT_AUTH_GRANT_B64='$(tr -d '\n' <"$PROVISION/agent-auth-grant.b64")'
USER_AUTH_GRANT_B64='$(tr -d '\n' <"$PROVISION/user-auth-grant.b64")'
USER_GRANT_BATCH_TURNS='${USER_GRANT_BATCH_TURNS:-16}'
EOF

echo "authority.sh: wrote $APP/.dev.vars (root=$ROOT_LOG_ID)"
echo "authority.sh: GRANT_AUTHORITY_TOKEN=$GRANT_AUTHORITY_TOKEN"
echo "authority.sh: scribe-worker's .dev.vars needs that token and GRANT_AUTHORITY_URL=http://localhost:$PORT"

# --test-scheduled exposes /__scheduled so the lease renewer can be driven by
# hand locally; deployed it is the cron trigger.
exec pnpm --filter grant-authority exec wrangler dev \
	--port "$PORT" --test-scheduled "$@"
